Administrador/Controllers/HomeController.cs
using CapaEntidad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaNegocio;


namespace Administrador.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Usuario()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarios()
        {
            List<Usuarios> oLista = new List<Usuarios>();
            oLista = new CN_Usuarios().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

    }
}

Administrador/Controllers/MantenimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Administrador.Controllers
{
    public class MantenimientoController : Controller
    {
        // GET: Mantenimiento
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }
    }
}

Administrador/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Administrador/Views/Home/Usuario.cshtml
@{
    ViewBag.Title = "Usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>
<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i>
        Lista de usuarios
    </div>
    <div class="card-body">
        <div class=" col-12">
            <button type="button" class="btn btn-success" onclick="abrirModal()"> Crear nuevo</button>
        </div>
        <hr />
        <table id="tabla" class="display cell-border" style=" width: 100%">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Correos</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLongTitle" b>Crear Usuario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6">
                        <label for="exampleFormControlInput1" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="txtNombres">
                    </div>
                    <div class="col-sm-6">
                        <label for="exampleFormControlInput1" class="form-label">Apellidos</label>
                        <input type="text" class="form-control" id="txtApellidos">
                    </div>
                    <div class="col-sm-6">
                        <label for="exampleFormControlInput1" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="txtCorreo">
                    </div>
                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option selected> </option>
                            <option value="1">Si</option>
                            <option value="2">No</option>
                        </select>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="NaN">Cerrar</button>
                <button type="button" class="btn btn-primary" oneclick="">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
    tabladata = $("#tabla").DataTable({
        responsive: true,
        ordering: false,
        "ajax": {
            url: '@Url.Action("ListarUsuarios","Home")',
            type: "GET",
            datatype: "json"
        },
        "columns": [
            { "data": "Nombre_Usuario" },
            { "data": "Apellido_Usuario" },
            { "data": "Correo" },
            {
                "data": "Activo", "render": function (valor) {
                    if (valor) {
                        return '<span class="badge bg-success">Si</span>';
                    } else {
                        return '<span class="badge bg-danger">No</span>';
                    }
                }
            },
            {
                "defaultContent": '<div class="text-center">' +
                    '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                    '<button type="button" class="btn btn-danger btn-sm ms-3"><i class="fas fa-trash"></i></button>' +
                    '</div>',
                    "orderable": false,
                "searchable": false,
                "width": "90px"
            }
        ],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.13.5/i18n/es-ES.json"
        }

    });

        function abrirModal() {
            $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar',function () {
            var filaseleccionada = $(this).closest("tr")

            console.log(tabladata.row(filaseleccionada).data());
        });
    </script>

}

Administrador/Views/Mantenimiento/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categoria</h2>

Administrador/Views/Mantenimiento/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marca</h2>

Administrador/Views/Mantenimiento/Producto.cshtml
@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Producto</h2>

Administrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mr. Shoes</title>
    @Styles.Render("~/Content/css")
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Mr. Shoes</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item disabled">Correo Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href=@Url.Action("Usuario", "Home")>
                            <div class="sb-nav-link-icon"><i class="fas fa-user-alt"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Categoria","Mantenimiento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" href="@Url.Action("Marca","Mantenimiento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mantenimiento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>